// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gehvpwdlqqbcyucikpil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlaHZwd2RscXFiY3l1Y2lrcGlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDc2NzEsImV4cCI6MjA3MTc4MzY3MX0.UogPKYmqK655AHG0Aj5c51Qr6gM-W2cPGDaxE2HFQQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});